// Copyright (c) 2019 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c1ef1dbc84a684543e8adbefbfff3c70291bbf3b$
//

#include "libcef_dll/ctocpp/spell_check_handler_ctocpp.h"
#include "libcef_dll/shutdown_checker.h"

// VIRTUAL METHODS - Body may be edited by hand.

NO_SANITIZE("cfi-icall")
void CefSpellCheckHandlerCToCpp::GetLanguageCode(CefString& lang) {
  shutdown_checker::AssertNotShutdown();

  cef_spell_check_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, get_language_code))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->get_language_code(_struct, lang.GetWritableStruct());
}

NO_SANITIZE("cfi-icall")
bool CefSpellCheckHandlerCToCpp::IsWordMisspelled(const CefString& word) {
  shutdown_checker::AssertNotShutdown();

  cef_spell_check_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, is_word_misspelled))
    return false;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Verify param: word; type: string_byref_const
  DCHECK(!word.empty());
  if (word.empty())
    return false;

  // Execute
  int _retval = _struct->is_word_misspelled(_struct, word.GetStruct());

  // Return type: bool
  return _retval ? true : false;
}

// CONSTRUCTOR - Do not edit by hand.

CefSpellCheckHandlerCToCpp::CefSpellCheckHandlerCToCpp() {}

// DESTRUCTOR - Do not edit by hand.

CefSpellCheckHandlerCToCpp::~CefSpellCheckHandlerCToCpp() {
  shutdown_checker::AssertNotShutdown();
}

template <>
cef_spell_check_handler_t* CefCToCppRefCounted<
    CefSpellCheckHandlerCToCpp,
    CefSpellCheckHandler,
    cef_spell_check_handler_t>::UnwrapDerived(CefWrapperType type,
                                              CefSpellCheckHandler* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

template <>
CefWrapperType CefCToCppRefCounted<CefSpellCheckHandlerCToCpp,
                                   CefSpellCheckHandler,
                                   cef_spell_check_handler_t>::kWrapperType =
    WT_SPELL_CHECK_HANDLER;
