// Copyright (c) 2017 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//

#include "libcef_dll/ctocpp/touch_action_handler_ctocpp.h"


// VIRTUAL METHODS - Body may be edited by hand.

void CefTouchActionHandlerCToCpp::HandleAction(CefString& action) {
  cef_touch_action_handler_t* _struct = GetStruct();
  if (CEF_MEMBER_MISSING(_struct, handle_action))
    return;

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  // Execute
  _struct->handle_action(_struct,
      action.GetWritableStruct());
}


// CONSTRUCTOR - Do not edit by hand.

CefTouchActionHandlerCToCpp::CefTouchActionHandlerCToCpp() {
}

template<> cef_touch_action_handler_t* CefCToCpp<CefTouchActionHandlerCToCpp,
    CefTouchActionHandler, cef_touch_action_handler_t>::UnwrapDerived(
    CefWrapperType type, CefTouchActionHandler* c) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

#ifndef NDEBUG
template<> base::AtomicRefCount CefCToCpp<CefTouchActionHandlerCToCpp,
    CefTouchActionHandler, cef_touch_action_handler_t>::DebugObjCt = 0;
#endif

template<> CefWrapperType CefCToCpp<CefTouchActionHandlerCToCpp,
    CefTouchActionHandler, cef_touch_action_handler_t>::kWrapperType =
    WT_TOUCH_ACTION_HANDLER;
