// Copyright (c) 2018 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=f5652210c9f0303ede67db2176b1e27815ceea51$
//

#ifndef CEF_LIBCEF_DLL_CPPTOC_TOUCH_ACTION_HANDLER_CPPTOC_H_
#define CEF_LIBCEF_DLL_CPPTOC_TOUCH_ACTION_HANDLER_CPPTOC_H_
#pragma once

#if !defined(WRAPPING_CEF_SHARED)
#error This file can be included wrapper-side only
#endif

#include "include/capi/cef_touch_action_handler_capi.h"
#include "include/cef_touch_action_handler.h"
#include "libcef_dll/cpptoc/cpptoc_ref_counted.h"

// Wrap a C++ class with a C structure.
// This class may be instantiated and accessed wrapper-side only.
class CefTouchActionHandlerCppToC
    : public CefCppToCRefCounted<CefTouchActionHandlerCppToC,
                                 CefTouchActionHandler,
                                 cef_touch_action_handler_t> {
 public:
  CefTouchActionHandlerCppToC();
};

#endif  // CEF_LIBCEF_DLL_CPPTOC_TOUCH_ACTION_HANDLER_CPPTOC_H_
