// Copyright (c) 2019 The Chromium Embedded Framework Authors. All rights
// reserved. Use of this source code is governed by a BSD-style license that
// can be found in the LICENSE file.
//
// ---------------------------------------------------------------------------
//
// This file was generated by the CEF translator tool. If making changes by
// hand only do so within the body of existing method and function
// implementations. See the translator.README.txt file in the tools directory
// for more information.
//
// $hash=c90c11103019165add9386914922fb9d6304bcdf$
//

#include "libcef_dll/cpptoc/touch_action_handler_cpptoc.h"
#include "libcef_dll/shutdown_checker.h"

namespace {

// MEMBER FUNCTIONS - Body may be edited by hand.

void CEF_CALLBACK
touch_action_handler_handle_action(struct _cef_touch_action_handler_t* self,
                                   cef_string_t* action) {
  shutdown_checker::AssertNotShutdown();

  // AUTO-GENERATED CONTENT - DELETE THIS COMMENT BEFORE MODIFYING

  DCHECK(self);
  if (!self)
    return;
  // Verify param: action; type: string_byref
  DCHECK(action);
  if (!action)
    return;

  // Translate param: action; type: string_byref
  CefString actionStr(action);

  // Execute
  CefTouchActionHandlerCppToC::Get(self)->HandleAction(actionStr);
}

}  // namespace

// CONSTRUCTOR - Do not edit by hand.

CefTouchActionHandlerCppToC::CefTouchActionHandlerCppToC() {
  GetStruct()->handle_action = touch_action_handler_handle_action;
}

// DESTRUCTOR - Do not edit by hand.

CefTouchActionHandlerCppToC::~CefTouchActionHandlerCppToC() {
  shutdown_checker::AssertNotShutdown();
}

template <>
CefRefPtr<CefTouchActionHandler> CefCppToCRefCounted<
    CefTouchActionHandlerCppToC,
    CefTouchActionHandler,
    cef_touch_action_handler_t>::UnwrapDerived(CefWrapperType type,
                                               cef_touch_action_handler_t* s) {
  NOTREACHED() << "Unexpected class type: " << type;
  return NULL;
}

template <>
CefWrapperType CefCppToCRefCounted<CefTouchActionHandlerCppToC,
                                   CefTouchActionHandler,
                                   cef_touch_action_handler_t>::kWrapperType =
    WT_TOUCH_ACTION_HANDLER;
